import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ReactNode } from "react";
import { cn } from "@/lib/utils";
import { SmoothScrolling } from "@/providers/smooth-scrolling";
import { Footer, Navbar } from "@/components/shared";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Short Flix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn(montserrat?.className, "antialiased")}>
        <SmoothScrolling>
          <Navbar />
          {children}
          <Footer />
        </SmoothScrolling>
      </body>
    </html>
  );
}
